@altinn_transformer_HostAddress = https://localhost:7157

POST {{altinn_transformer_HostAddress}}/transform/
Accept: application/json
Content-Type: application/json

{
  "inputType": "urn:altinn:raw-value",
  "inputValue": 12345678,
  "requestedOutputType": "urn:altinn:secured-data",
  "securitySettings": {
    "requiresOrgNo": [
      "912345678"
    ]
  }
}

